# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kilncode
tagline:          Thoughts on the Creation of Software
description:      Thoughts on the Creation of Software
url: http://klincode.com


paginate:         5
